// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {habits} from '../models';

export function AddHabit(arg1:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetCurrentWeekHabits():Promise<habits.WeeklyHabits>;

export function Greet(arg1:string):Promise<string>;

export function RemoveHabit(arg1:string):Promise<void>;

export function ReorderHabits(arg1:Array<string>):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SelectWorkspaceDirectory():Promise<string>;

export function ToggleHabit(arg1:string):Promise<void>;

export function ValidateWorkspacePath(arg1:string):Promise<void>;
