// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetConfig():Promise<config.Config>;

export function Greet(arg1:string):Promise<string>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SelectWorkspaceDirectory():Promise<string>;

export function ValidateWorkspacePath(arg1:string):Promise<void>;
