// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHabit(arg1) {
  return window['go']['main']['App']['AddHabit'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentWeekHabits() {
  return window['go']['main']['App']['GetCurrentWeekHabits']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RemoveHabit(arg1) {
  return window['go']['main']['App']['RemoveHabit'](arg1);
}

export function ReorderHabits(arg1) {
  return window['go']['main']['App']['ReorderHabits'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectWorkspaceDirectory() {
  return window['go']['main']['App']['SelectWorkspaceDirectory']();
}

export function ToggleHabit(arg1) {
  return window['go']['main']['App']['ToggleHabit'](arg1);
}

export function ValidateWorkspacePath(arg1) {
  return window['go']['main']['App']['ValidateWorkspacePath'](arg1);
}
