name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [frontend, backend]
    name: ${{ matrix.component }} tests
    steps:
    - uses: actions/checkout@v4
    
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    # Setup component-specific dependencies
    - name: Setup ${{ matrix.component }} dependencies
      run: make setup-${{ matrix.component }}
    
    # Run component tests
    - name: Run ${{ matrix.component }} tests
      run: make test-${{ matrix.component }}

  hygiene:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [frontend, backend]
    name: ${{ matrix.component }} hygiene
    steps:
    - uses: actions/checkout@v4
    
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    # Setup component-specific dependencies
    - name: Setup ${{ matrix.component }} dependencies
      run: make setup-${{ matrix.component }}
    
    # Run component hygiene checks
    - name: Run ${{ matrix.component }} hygiene
      run: make hygiene-${{ matrix.component }}

    # Check git state
    - name: Check if git working tree is dirty
      run: make dirty

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    # Setup frontend dependencies for build
    - name: Setup dependencies
      run: make setup

    # Build the application
    - name: Build application
      run: make build
